name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make libcurl4-openssl-dev

      - name: Build
        run: make

      - name: Archive binary
        run: tar -czvf ${GITHUB_REPOSITORY#*/}-${GITHUB_REF_NAME}-linux.tar.gz dirleaks

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dirleaks-linux
          path: ./${GITHUB_REPOSITORY#*/}-${GITHUB_REF_NAME}-linux.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dirleaks-linux
          path: ./

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./${GITHUB_REPOSITORY#*/}-${GITHUB_REF_NAME}-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
